# Generated by Django 5.2.5 on 2026-06-27 23:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_covers'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_logos'),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_images'),
        ),
    ]
