# Generated by Django 6.0.6 on 2026-06-28 01:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0002_alter_product_image_alter_restaurant_cover_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "قائمة", "verbose_name_plural": "القوائم"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "منتج", "verbose_name_plural": "المنتجات"},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"verbose_name": "مطعم", "verbose_name_plural": "المطاعم"},
        ),
        migrations.AlterModelOptions(
            name="restaurantcategory",
            options={"verbose_name": "فئة مطعم", "verbose_name_plural": "فئات المطاعم"},
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={"verbose_name": "وقت عمل", "verbose_name_plural": "أوقات العمل"},
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=3, verbose_name="تقييم المنتج"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="رسوم التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="وقت التوصيل التقديري (دقيقة)"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurants",
                to="restaurants.restaurantcategory",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان العرض")),
                ("description", models.TextField(blank=True, verbose_name="وصف العرض")),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="promotion_images",
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(default=0, verbose_name="نسبة الخصم %"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="restaurants.restaurant",
                        verbose_name="المطعم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عرض ترويجي",
                "verbose_name_plural": "العروض الترويجية",
                "ordering": ["-created_at"],
            },
        ),
    ]
