# Generated by Django 5.2.5 on 2026-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
